### ISSUE TITLE
测试视频格式有要求吗？为什么测试结果只有Alive

### ISSUE THREAD

**Issue by HisZ** [ZJUTSong/Alive_Detect#1]

**Comment by HisZ** [comment]
测试用得ipad显示均为alive 训练集问题吗

**Comment by ZJUTSong** [comment]
输入的格式没有要求，模型能推理出结果就行，不过我也不敢说所有的格式都支持，但是常见的都可以。结果都是活体，有可能视频帧频率较快，偶尔有个非活体检测结果一闪而过看不到，你可以尝试拍摄的视频人脸角度刁钻一些，然后保存的视频帧频率设置慢一些，这样模型就可能在某几个角度下的推理结果错判成非活体，视频帧频率慢一些就能看到了，如果是非活体检测结果是红框。数据集没啥问题，建议自己跑跑看哈~
